#!/bin/bash
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
KEYS_DIR="$HOME/.ssh"
PRIVATE_KEY="$KEYS_DIR/revint-private.pem"
PUBLIC_KEY="$KEYS_DIR/revint-public.pem"
ENV_FILE="$SCRIPT_DIR/../.env"

# Check for session description
if [ -z "$1" ]; then
    echo "Usage: $0 <session-description>"
    echo "Example: $0 'My Awesome Presentation'"
    exit 1
fi

SESSION_NAME="$1"
SESSION_DATE=$(date +%Y-%m-%d)

# Create keys directory if it doesn't exist
mkdir -p "$KEYS_DIR"

# Generate keys if they don't exist
if [ ! -f "$PRIVATE_KEY" ]; then
    echo "Generating new key pair..."
    openssl genrsa -out "$PRIVATE_KEY" 2048 2>/dev/null
    openssl rsa -in "$PRIVATE_KEY" -pubout -out "$PUBLIC_KEY" 2>/dev/null
    echo "Keys generated in $KEYS_DIR"
else
    echo "Using existing keys from $KEYS_DIR"
fi

# Create payload
PAYLOAD=$(jq -c -n \
    --arg name "$SESSION_NAME" \
    --arg date "$SESSION_DATE" \
    '{name: $name, date: $date}')

echo "Payload: $PAYLOAD"

# Base64url encode payload
PAYLOAD_B64=$(echo -n "$PAYLOAD" | base64 -w0 | tr '+/' '-_' | tr -d '=')

# Sign payload and base64url encode signature
SIGNATURE_B64=$(echo -n "$PAYLOAD" | openssl dgst -sha256 -sign "$PRIVATE_KEY" | base64 -w0 | tr '+/' '-_' | tr -d '=')

# Create token
TOKEN="${PAYLOAD_B64}.${SIGNATURE_B64}"

# Write public key to .env file for Docker
echo "# Auto-generated by create-session.sh" > "$ENV_FILE"
echo "PUBLIC_KEY=\"$(cat "$PUBLIC_KEY" | tr '\n' '|')\"" >> "$ENV_FILE"

echo ""
echo "============================================"
echo "Session created successfully!"
echo "============================================"
echo ""
echo "Token:"
echo "$TOKEN"
echo ""
echo "Public key written to: $ENV_FILE"
echo ""
echo "To start the session:"
echo "  1. Deploy: npm run deploy"
echo "  2. Create session: curl -X POST http://localhost:3000/api/v1/session/new/$TOKEN"
echo ""
